### ISSUE TITLE
What are 'b' and 'pricing function' arguments for numerical greeks

### ISSUE THREAD

**Issue by andr3w321** [vollib/py_vollib#15]
What are 'b' and 'pricing function' arguments for numerical greeks and how do you pass them as arguments? My understanding is you should be using numerical_delta() instead of analytical delta function for faster, but slightly less accurate results.

```
from py_vollib.helpers.numerical_greeks import delta as numerical_delta
from py_vollib.black_scholes.greeks.analytical import delta

S = 49
K = 50 
r = .05
t = 0.3846
sigma = 0.2
flag = 'c'

delta(flag, S, K, t, r, sigma)
numerical_delta(flag, S, K, t, r, sigma)

```
Results
```
>>> delta(flag, S, K, t, r, sigma)
0.5216016339715761
>>> numerical_delta(flag, S, K, t, r, sigma)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: delta() missing 2 required positional arguments: 'b' and 'pricing_function'
```

**Comment by lbrichards** [comment]
The py_vollib.helpers module is not intended to be called directly.  (Which is why it is undocumented.)
Instead use 
`from py_vollib.black_scholes.greeks.numerical import delta as numerical_delta` and all will be fine.  The b argument is due to that inside helpers we are using a generalized form (borrowed from Espen Haug) that accepts black-scholes-merton, and other option pricing formulae.
