### ISSUE TITLE
Strike from IV and delta

### ISSUE THREAD

**Issue by micycle1** [vollib/py_vollib#21]
Options implied volatility data is often given in terms of delta of the contracts (and not their strike).
However, the option strike is required to price the option (using `py_vollib.black_scholes`).

Can strike be computed from iv and delta (along with other parameters) with _py_vollib_?

**Comment by lbrichards** [comment]
Strike is an input for the functions in this library, not an output.  Generally strike would not be uniquely identified by a specific iv value.  Consider the IV smile, in which the same iv values appear both left and right of ATM.  For this reason, you could create a mapping between IV and strike, but it would not be one-to-one.  For delta the user of this library should be able to obtain a unique strike from a single value of delta for a given maturity, since option delta is a monotonically non-decreasing function.  For asymptotic strikes the delta-to-strike mapping might not be one-to-one, so exercise some caution.
