### ISSUE TITLE
BelowIntrinsicValue exception for Deep in the money put

### ISSUE THREAD

**Issue by shuara** [vollib/py_vollib#7]
Hi,
I am using your package to calculate all the greeks and also the IV for deribit btc usd options. but I am facing issues with evaulating deep in the money puts or out of the money calls.
I am getting the exception : BelowIntrinsicValue. kindly help me how can I overcome this exception which is coming from the code lets_be_rational.py

Regards
Shubha

**Comment by lbrichards** [comment]
First of all, it is always a good idea to read Peter Jaeckel's paper "Lets Be Rational," as this can clear up some misunderstandings.  Next, please note that lets_be_rational is only for European style expiration.  If you are dealing with American options, you will often encounter prices that simply don't make sense in the European context.  
There are prices which simply don't make sense, and for which no implied volatility can be calculated.  Having said that, such prices do occur in the wild, and we often just have to deal with them.  How the exceptions are handled vary from one data vendor to another.  Many will simply set the IV to zero.  The alternative is to sanitize the prices using your model of choice.  (I often use SVI due to its ease of calibration).  Hope this helps.
Larry
